### ISSUE TITLE
Horizontally Align Meetups by Meetup Name

### ISSUE THREAD

**Issue by MegTheDev** [lansingcodes/www#107]
**Is your feature request related to a problem? Please describe.**
The meetups appear to be aligned vertically but not horizontally, causing the list/cards to be very disorganized.

**Describe the solution you'd like**
I would recommend aligning by group name as group names are always one line, while icons and group descriptions can be different sizes depending on content.

**Additional context**
![image](https://user-images.githubusercontent.com/56272543/66363912-e7164880-e955-11e9-9032-4e4dbc916b61.png)

**Comment by bretself** [comment]
PR merged
