### ISSUE TITLE
Selenium tests fail to run

### ISSUE THREAD

**Issue by joeryan** [lansingcodes/www#112]
**Describe the bug**
Selenium fails to run firefox and chrome tests

**To Reproduce**
nvm use lts/dubnium
npm install
npm test
>>> fail to start selenium session for chrome 77 and firefox 69

**Expected behavior**
Tests to run successfully
**Screenshots**

**Environment (please complete the following information):**
 - Macair 2015
 - OS: [Mac OSX 10.14.6]
 - Browser [chrome 77, firefox 69]
 - Version [77, 69]

**Additional context**
node version 10.15.0

**Comment by egillespie** [comment]
Hi @joeryan, there is no `test` script in `package.json`:

``` json
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "lintfix": "eslint --fix --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
```

Do you have the latest copy of the `www` project, or are you introducing tests?

**Comment by joeryan** [comment]
I thought I did, since I pulled it down on Tuesday.  But that's not what my package.json looks like, so I must be mistaken.  I'll rebase my local copy and ensure I have the latest code.  If there are no tests, then I suppose it should be closed and I'll open up one to write at least some minimal tests.  I like to see at least something before I start in, but writing them is just as good.

**Comment by joeryan** [comment]
Invalid bug report, user error.
