### ISSUE TITLE
Node Sass : OS X 64-bit with Unsupported runtime (64)

### ISSUE THREAD

**Issue by dhcrain** [lansingcodes/www#12]
ERROR in Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-50fae52a&scoped=true!./~/sass-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./~/eslint-loader!./src/components/resource-section.vue 4:14-324 13:2-17:4 14:20-330

After `yarn install` and then `yarn dev` get the error from above. 
On MacOS 10.13.6 
node 10.11.0 
npm 6.4.1
yarn 1.10.1

**Comment by egillespie** [comment]
Fixed by PR #13. Thanks!
