### ISSUE TITLE
Resolve security issues

### ISSUE THREAD

**Issue by MegTheDev** [lansingcodes/www#130]
Update to latest versions of the following dependencies:
* bl - https://github.com/lansingcodes/www/network/alert/package-lock.json/bl/open
* yars-parser - https://github.com/lansingcodes/www/network/alert/package-lock.json/yargs-parser/open
* http-proxy - https://github.com/lansingcodes/www/network/alert/package-lock.json/http-proxy/open
* handlebars - https://github.com/lansingcodes/www/network/alert/package-lock.json/handlebars/open
* lodash.merge - https://github.com/lansingcodes/www/network/alert/package-lock.json/lodash.mergewith/open
* node-sass - https://github.com/lansingcodes/www/network/alert/package-lock.json/node-sass/open
* lodash. defaultsdeep - https://github.com/lansingcodes/www/network/alert/package-lock.json/lodash.defaultsdeep/open
* hapi - https://github.com/lansingcodes/www/network/alert/package-lock.json/hapi/open
* ammo - https://github.com/lansingcodes/www/network/alert/package-lock.json/ammo/open
* puppeteer - https://github.com/lansingcodes/www/network/alert/package-lock.json/puppeteer/open
* bump lodash - https://github.com/lansingcodes/www/pull/128#event-3553996541

**Comment by egillespie** [comment]
Running `npm audit` will also show which dependencies have vulnerabilities, and you can try to run `npm audit --fix` to attempt to automatically update them as well.
