### ISSUE TITLE
Show events on current date even after their start time

### ISSUE THREAD

**Issue by egillespie** [lansingcodes/www#141]
**Describe the bug**

Once an event starts, it stops appearing in the calendar on the Lansing Codes website. It appears that the calendar only shows events that are in the future based on the current time.

**Expected behavior**

All events for the current day should remain on the calendar until the day ends. This makes it easier to quickly look up an event that you may be running late to or need to look up details such as the location.

**Screenshots**

This screenshot was taken at 6:38 pm during the "Lansing Codes Together" event. The event does not appear in the calendar.

![image](https://user-images.githubusercontent.com/5572255/127405132-b79307c1-06e8-49ab-9615-6b74e6e3624c.png)

**Additional context**

It looks like the [`isDuringActivePeriod` function](https://github.com/lansingcodes/www/blob/main/components/event-calendar.vue#L161) is already attempting to determine if an event occurs on the same day in order to show it. This would be a good starting place to see why events on the current date do not appear once the event starts (if that is the real reason they disappear).

**Comment by joeryan** [comment]
Could not duplicate issue.  Site still showed Hacktoberfest 6pm event at 9:23 pm.
