### ISSUE TITLE
Link to Facebook and Twitter accounts on `www`

### ISSUE THREAD

**Issue by egillespie** [lansingcodes/www#20]
Facebook: https://www.facebook.com/LansingCodes/
Twitter: https://twitter.com/lansingcodes

Optional:
Email: lansingcodes@gmail.com
GitHub: https://github.com/lansingcodes

Ideally these links would go in the navbar at the top of the page as well as in the footer.

**Comment by bretself** [comment]
@egillespie The www footer contact link currently goes to humanitycodes@gmail.com. Do you want this changed to point to lansingcodes@gmail.com?

**Comment by egillespie** [comment]
> @egillespie The www footer contact link currently goes to [humanitycodes@gmail.com](mailto:humanitycodes@gmail.com). Do you want this changed to point to [lansingcodes@gmail.com](mailto:lansingcodes@gmail.com)?

Yes, please!
