### ISSUE TITLE
Add newsletter signup form

### ISSUE THREAD

**Issue by egillespie** [lansingcodes/www#23]
Lansing Codes is starting a newsletter soon! It would be nice if visitors have a chance to sign up for it somewhere at the top of the Lansing.Codes homepage.

The following code can be used as a start for a signup form. It was provided by MailChimp, where the contact list is maintained. There are also frameworks for doing MailChimp signup forms with AJAX. Something like that would be great so users don't have to leave the page when submitting the signup form.

``` html
<!-- Begin Mailchimp Signup Form -->
<div id="mc_embed_signup">
<form action="https://codes.us19.list-manage.com/subscribe/post?u=284c94c0d64272db7f56f4c6d&amp;id=f13ffe3703" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address </label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_284c94c0d64272db7f56f4c6d_f13ffe3703" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
```

**Comment by kentyunge** [comment]
@egillespie Any way I could get access to the MailChimp account so I can verify requests?

**Comment by kentyunge** [comment]
Opened an issue on the API project to add a subscribe endpoint.  Not much a ruby developer so I'm looking for some help on this issue.

https://github.com/lansingcodes/api/issues/24

**Comment by kentyunge** [comment]
@egillespie Looking at the `ajaxChimp` documentation I found this

>**Note**: This relies on an undocumented feature at mailchimp that uses JSONP to allow cross-domain ajax to work. You have been warned. (It has however, been around for at least 3 years that I know of, and probably more.)

No wonder, I couldn't find a way around this.  I will look into this

**Comment by egillespie** [comment]
@kentyunge LOL! I don't recall reading that when I started using ajaxChimp on givingjar.org, but I just tested the AJAX signup and it still works. :)
