### ISSUE TITLE
Add sponsorship form or link

### ISSUE THREAD

**Issue by egillespie** [lansingcodes/www#49]
It would be nice to offer a form, either on the main page or on a separate page, to allow businesses to contact us if they are interested in sponsoring us in any way.

I don't have a specific idea for how this should look or work, but I think it would be helpful to make the form open in a separate page/tab or perhaps in a modal that appears on the page only after clicking a link. This will help us keep the length of the main page from becoming too long.

The following information would be helpful to collect from potential sponsors:

* Contact name
* Email address
* Organization name (optional)
* What would they like to sponsor?
   - Food and drinks
   - Venue
   - Other (text field)
* Frequency of sponsorship
   - One time
   - Recurring
   - Other (text field)

@KatieMFritz had created such a form/spreadsheet once upon a time. One of us will update the list of fields if/when she's able to locate it.

**Comment by KatieMFritz** [comment]
Form is being revised at https://lansingcodes.typeform.com/to/ltKNRy. We just need a button that opens it!

**Comment by jnktsn** [comment]
I created pull request #56 adding the button that links to the page above.  Let me know if I should make any other changes to it.
