### ISSUE TITLE
Implement new design in Nuxt

### ISSUE THREAD

**Issue by KatieMFritz** [lansingcodes/www#57]
Latest and greatest; use Tailwind.

**Comment by KatieMFritz** [comment]
Update: It's coming along! Erik and I are implementing @kentyunge's design ideas from #51 using Tailwind in a Nuxt.js setup with recent tooling. We'll open it up for reviews & more polishing soon!

**Comment by kentyunge** [comment]
@KatieMFritz How is this going?  Is there anything in particular you need help with?

**Comment by KatieMFritz** [comment]
Hi @kentyunge , sorry I didn't see your comment a whole month ago! The project was on ice for a few weeks, but @egillespie and I are back at it today. It's getting very close.

**Comment by egillespie** [comment]
Hey guess what? The new design is live!

I'm going to close this and will plan on addressing individual bugs/features in separate issues.

@kentyunge, thank you so much for offering up this slick design. I know the results don't exactly match, but I did my best and am happy to receive feedback.

@KatieMFritz, thanks for the help choosing Nuxt and charging forward with the implementation. Samesies if you have tips — I'd love to hear about them!
