### ISSUE TITLE
Update http links to https

### ISSUE THREAD

**Issue by bretself** [lansingcodes/www#58]
Many of the external links (largely meetup.com) are links as http. These get redirected with a 301 to their https (secure) version. Let's change these to https and save the redirect delay for the user. 

To find the links in question, run the site through https://validator.w3.org (or your link checker of choice)

Results of scan on 2018-10-24 ~6:45pm

List of redirects
The links below are not broken, but the document does not use the exact URL, and the links were redirected. It may be a good idea to link to the final location, for the sake of speed.

warning Line: 4 http://www.meetup.com/Lansing-Area-R-Users-Group/ redirected to https://www.meetup.com/Lansing-Area-R-Users-Group/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4 http://www.meetup.com/Mid-Michigan-Code-Retreat/ redirected to https://www.meetup.com/Mid-Michigan-Code-Retreat/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4 http://www.meetup.com/lansingweb/ redirected to https://www.meetup.com/lansingweb/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4 http://www.meetup.com/Lansing-DevOps-Meetup/ redirected to https://www.meetup.com/Lansing-DevOps-Meetup/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4 http://www.meetup.com/PMI-Capital-Area-Chapter-Lunch-and-Learn/ redirected to https://www.meetup.com/PMI-Capital-Area-Chapter-Lunch-and-Learn/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4 http://www.meetup.com/Lansing-Javascript-Meetup/ redirected to https://www.meetup.com/Lansing-Javascript-Meetup/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4 http://www.meetup.com/GLASS-Greater-Lansing-Area-for-SQL-Server/ redirected to https://www.meetup.com/GLASS-Greater-Lansing-Area-for-SQL-Server/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4 http://www.meetup.com/GLUGnet/ redirected to https://www.meetup.com/GLUGnet/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4 http://www.meetup.com/lansing-tech-demos/ redirected to https://www.meetup.com/lansing-tech-demos/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 11 http://www.rmcagency.com/ redirected to https://www.rmcagency.com/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4 http://www.meetup.com/LansingAreaSoftwareTesters/ redirected to https://www.meetup.com/LansingAreaSoftwareTesters/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4 http://slack.lansing.codes/ redirected to https://slack.lansing.codes/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

warning Line: 4 http://www.meetup.com/Mid-Michigan-Agile-Group/ redirected to https://www.meetup.com/Mid-Michigan-Agile-Group/
Status: 301 -> 200 OK
This is a permanent redirect. The link should be updated.

**Comment by brendonthiede** [comment]
Wherever possible, links to external sites have been switched to use https, though some sites don't have a secure site at this time (www.mmcfug.org, lansingmi.issa.org, and www.purelansing.com)
